image: python:3.9-slim

stages:
  - tasks

services:
  - name: postgres:15-alpine
    alias: postgres


variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST_AUTH_METHOD: trust

  DBNAME: postgres
  DBHOST: postgres
  DBPORT: 5432
  DBUSER: postgres
  DBPASSWORD: password


  PROJECT_DIR: ${CI_PROJECT_DIR}
  SCRIPTS_DIR: ${PROJECT_DIR}/scripts
  TESTS_DIR: ${PROJECT_DIR}/tests
  UTILS_DIR: ${PROJECT_DIR}/utils
  PYPSQL: ${UTILS_DIR}/pypsql.py

  NO_COLOUR: '\033[0m'
  LIGHT_RED: '\033[1;31m'


.setup:
  before_script:
    - pip install -r ${PROJECT_DIR}/requirements.txt > /dev/null 2> /dev/null


tasks from 3rd to 11th:
  stage: tasks
  extends:
    - .setup
  script:
    - echo -e "${LIGHT_RED}>>> Task №3 <<<${NO_COLOUR}"
    - python3 ${PYPSQL} --file="${SCRIPTS_DIR}/gradebook_ddl.sql" --cat

    - echo -e "${LIGHT_RED}>>> Task №4-5 <<<${NO_COLOUR}"
    - python3 ${PYPSQL} --file="${SCRIPTS_DIR}/gradebook_inserts.sql"

    - echo -e "${LIGHT_RED}>>> Task №6-7 <<<${NO_COLOUR}"
    - pytest ${TESTS_DIR}/test_selects.py

    - echo -e "${LIGHT_RED}>>> Task №9 <<<${NO_COLOUR}"
    - pytest ${TESTS_DIR}/test_views.py

    - echo -e "${LIGHT_RED}>>> Task №10 <<<${NO_COLOUR}"
    - pytest ${TESTS_DIR}/test_functions.py
